### ISSUE TITLE
Add sidetest.unitTest.prefix

### ISSUE THREAD

**Issue by meichthys** [matdurand/sidetest#1]
Some languages like Python have a convention to pre-pend `test_` to the test file names, rather than adding it before the extension. 

It would be nice if this extension could support this use case by adding a config setting called `sidetest.unitTest.prefix`. The value could default to null, but allow the user to choose what prefix to use.

**Comment by matdurand** [comment]
Seems like a good idea. I'll get back to you shortly. I'm trying to see if we could explore a bit more generic solution where one could provide the whole pattern instead of prefix/suffix and such. But maybe it's too complex. Let me a few days and I'll decide.
And thanks for the PR.

**Comment by meichthys** [comment]
I ended up finding https://marketplace.visualstudio.com/items?itemName=fxlipe115.switch which has pattern matching. 

My PR probably wasn't good javascript since iIve never dealt with it before.

**Comment by matdurand** [comment]
Look like a pretty good extension. Honestly I don't care that much about mine. I just wrote it because I wanted that feature and couldn't find it. Good to know there are alternatives!

**Comment by matdurand** [comment]
Fixed in 1.4.1
